FROM openjdk:8-jre

ENV ES_VERSION 6.0.1
ENV ES_HOME /opt/elasticsearch

### Install wget
RUN set -x \
 && apt-get update && apt-get install -y \
    wget \
 && rm -rf /var/lib/apt/lists/*

### Add group and user
RUN set -x \
	\
	&& groupadd elasticsearch \
	&& useradd -g elasticsearch elasticsearch

### Obtain ES 5.6.5 and put it into ELASTICSEARCH_HOME
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz \
 && tar -xzf elasticsearch-${ES_VERSION}.tar.gz \
 && mv elasticsearch-${ES_VERSION} ${ES_HOME} \
 && rm ./elasticsearch-${ES_VERSION}.tar.gz

### Update configuration file
ADD ./elasticsearch.yml ${ES_HOME}/config/elasticsearch.yml

### Export elasticsearch to PATH and change the own of the folder
ENV PATH ${ES_HOME}/bin:$PATH
RUN chown -R elasticsearch:elasticsearch ${ES_HOME}

### Change to certain group and user
USER elasticsearch:elasticsearch

EXPOSE 9200 9300
CMD ["elasticsearch"]
